### ISSUE TITLE
Estruturação do projeto do NestJS

### ISSUE THREAD

**Issue by vituhugo** [vituhugo/pizzeria-admin#1]
Aplicar arquitetura e configurar projeto.

```yaml
src:
    pizzas:
        modules:
            igredient
            category
            size
        models:
    clients:
        models
    orders:
        models
```
