### ISSUE TITLE
Definição arquitetura Back-end

### ISSUE THREAD

**Issue by vituhugo** [vituhugo/pizzeria-admin#3]
### [REST] Definição dos recursos e verbos disponíveis em cada um.
- ingredientes
	- POST
	- DELETE
	- GET
- pedidos
	- POST
	- GET
- pizzas
	- POST
	- GET
	- PUT
	- DELETE
- clientes
	- POST
	- GET
	- PUT
	- DELETE
- categorias
	- POST
	- PUT
	- GET
	- DELETE
- tamanhos
	- POST
	- PUT
	- DELETE

### [Nest] Definição da estrutura de pastas e os módulos a serem criados.

Modules/Submodules:
- Pizzas
	- Ingredientes
	- Categorias
	- Tamanhos
- Clientes
	- Clientes
- Pedidos
	- Orders

folder structure:
```yaml
src:
    pizzas:
        submodules:
            igredient
            category
            size
        models:
    clients:
        models
    orders:
        models
```
